name = "mode"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "00000000-0000-0000-0000-000000000000"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/SherlyKinan/inconigto-vpn/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/SherlyKinan/inconigto-vpn/refs/heads/main/web/sub.html"


